import type { Metadata } from "next";
import {  Inter } from "next/font/google";
import "./globals.css";
const InterFont = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={`${InterFont.variable} AAAAAA`} >
        {children}
      </body>
    </html>
  );
}
