import type { Metadata } from "next";
import { Merriweather } from "next/font/google";
import "./globals.css";
const RobotoSlabFont = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={`${RobotoSlabFont.variable} AAAAAA`} >
        {children}
      </body>
    </html>
  );
}
